default_view: "Main"

views:
  "Main":
    - title: "←"
      type: tmux
      action: previous-window
      color: green
      flash: false
    - title: "→"
      type: tmux
      action: next-window
      color: green
      flash: false
    - type: view
      action: System
      color: violet
    - type: view
      action: Git
      color: chartreuse
    - type: view
      action: Python
      color: rose
    - type: view
      action: NPM
      color: magenta
    - type: view
      action: ZPM
      color: yellow
    - type: view
      action: Docker
      color: springgreen
    - type: view
      action: Ops
      color: red

  "Git":
    - type: view
      action: Main
      color: azure
    - title: Git Status
      type: popup
      action: "git status"
      color: cyan
    - title: Git Branch
      type: popup
      action: git branch
      color: blue

  "Python":
    - type: view
      action: Main
      color: azure
    - text: Python Install
      type: popup
      action: "pip install"
      color: orange
    - title: Python CLI
      type: exec
      action: "python"
      color: cyan

  "NPM":
    - type: view
      action: Main
      color: azure
    - title: NPM list
      type: popup
      action: "npm ls"
      color: chartreuse
    - title: NPM Install
      type: popup
      action: "npm i"
      color: springgreen
    - title: Dev
      type: popup
      action: "npm run dev"
      color: cyan

  ZPM:
    - type: view
      action: Main
      color: azure
    - title: Upgrade Plugins
      type: popup
      action: "zpm upgrade"
      color: orange
    - title: Clean Cache
      type: popup
      action: "zpm clean"
      color: rose
    - title: Readme
      type: popup
      action: "zpm readme"
      color: violet

  System:
    - type: view
      action: Main
      color: azure
    - title_exec: _tmux_uname
      type: popup
      action: "neofetch"
      color: yellow
    - title_exec: _tmux_myip
      type: popup
      action: ip addr
      color: red

  Docker:
    - type: view
      action: Main
      color: azure
    - title: Docker PS
      type: popup
      action: "docker ps"
      color: cyan
    - title: Docker Images
      type: popup
      action: "docker images"
      color: orange
    - title: Compose Up
      type: popup
      action: "docker compose up"
      color: violet

  Ops:
    - type: view
      action: Main
      color: azure
    - title: Top
      type: popup
      action: "top"
      color: chartreuse
    - title: Disk Usage
      type: popup
      action: "df -h"
      color: springgreen
    - title: Journalctl
      type: popup
      action: "journalctl -xe"
      color: magenta
