default_view: "Main"
views:
  "Main":
    -
      title: '←'
      type: tmux
      command: previous-window
      color: green
      flash: false
    -
      title: '→'
      type: tmux
      command: next-window
      color: green
      flash: false
    -
      type: view
      command: System
      color: violet
    -
      type: view
      command: Git
      color: chartreuse
    -
      type: view
      command: Python
      color: rose
    -
      type: view
      command: ZPM
      color: yellow

  "Git":
    -
      type: view
      command: Main
    -
      title: Git Status
      type: exec
      command: "git status"
    -
      title: Git Branch
      type: exec
      command: git branch

  "Python":
    -
      type: view
      command: Main
    -
      text: Python Install
      type: insert
      command: 'pip install '
    -
      title: Python
      type: view
      command: "python"


  "NPM":
    -
      type: view
      command: Main
    -
      title: NPM list
      type: exec
      command: "npm ls"
    -
      title: NPM Install
      type: insert
      command: 'npm i '
    -
      title: Main
      type: view
      command: "Main"

  ZPM:
    -
      type: view
      command: Main
    -
      title: Upgrade Plugins
      type: exec
      command: "zpm upgrade"
    -
      title: Clean Cache
      type: exec
      command: "zpm clean"
    -
      title: Readme
      type: insert
      command: "zpm readme"

  System:
    -
      type: view
      command: Main
    -
      title_exec: _tmux_uname
      type: exec
      command: "neofetch"
      color: yellow
    -
      title_exec: _tmux_myip
      type: insert
      command: ip addr
      color: red
    -
      title: Menu
      type: view
      command: Menu
      color: blue
