default_view: "Main"
views:
  "Main":
    1:
      title: '←'
      type: tmux
      command: previous-window
      color: green
    2:
      title: '→'
      type: tmux
      command: next-window
      color: green
    3:
      title_exec: _tmux_uname
      type: exec
      command: "neofetch"
      color: yellow
    4:
      title_exec: _tmux_myip
      type: exec
      command: ip addr
      color: red
    5:
      title: Menu
      type: view
      command: Menu
      color: blue

  "Menu":
    1:
      title: Git
      type: view
      command: "Git"
    2:
      title: Python
      type: view
      command: "Python"
    3:
      title: NPM
      type: view
      command: "NPM"
    4:
      title: ZPM
      type: view
      command: "ZPM"
    5:
      title: Main
      type: view
      command: "Main"
      color: green

  "Git":
    1:
      title: Menu
      type: view
      command: "Menu"
    2:
      title: Git Status
      type: exec
      command: "git status"
    3:
      title: Git Branch
      type: exec
      command: git branch
    4:
      title: Menu
      type: view
      command: "Menu"
    5:
      title: Main
      type: view
      command: "Main"
      color: green

  "Python":
    1:
      title: Menu
      type: view
      command: "Menu"
    2:
      title: Python list
      type: exec
      command: "npm ls"
    3:
      text: Python Install
      type: insert
      command: 'npm i '
    4:
      title: Python
      type: view
      command: "Python"
    5:
      title: Main
      type: view
      command: "Main"
      color: green

  "NPM":
    1:
      title: Menu
      type: view
      command: "Menu"
    2:
      title: NPM list
      type: exec
      command: "npm ls"
    3:
      title: NPM Install
      type: insert
      command: 'npm i '
    4:
      title: Main
      type: view
      command: "Main"
    5:
      title: Main
      type: view
      command: "Main"
      color: green

  "ZPM":
    1:
      title: Menu
      type: view
      command: "Menu"
    2:
      title: Upgrade Plugins
      type: exec
      command: "zpm upgrade"
    3:
      title: Clean Cache
      type: exec
      command: "zpm clean"
    4:
      title: Readme
      type: insert
      command: "zpm readme"
    5:
      title: Main
      type: view
      command: "Main"
      color: green
