default_view: "Main"
views:
  "Main":
    1:
      text: '←'
      tmux_command: previous-window
      color: green
    2:
      text: '→'
      tmux_command: next-window
      color: green
    3:
      text_exec: _tmux_uname
      command: "neofetch"
      color: yellow
    4:
      text_exec: _tmux_myip
      command: ip addr
      color: red
    5:
      text: Menu
      view: Menu
      color: blue

  "Menu":
    1:
      text: Git
      view: "Git"
    2:
      text: Python
      view: "Python"
    3:
      text: NPM
      view: "NPM"
    4:
      text: ZPM
      view: "ZPM"
    5:
      text: Main
      view: "Main"
      color: green

  "Git":
    1:
      text: Menu
      view: "Menu"
    2:
      text: Git Status
      command: "git status"
    3:
      text: Git Branch
      command: git branch
    4:
      text: Menu
      view: "Menu"
    5:
      text: Main
      view: "Main"
      color: green

  "Python":
    1:
      text: Menu
      view: "Menu"
    2:
      text: Python list
      command: "npm ls"
    3:
      text: Python Install
      template: 'npm i '
    4:
      text: Python
      view: "Python"
    5:
      text: Main
      view: "Main"
      color: green

  "NPM":
    1:
      text: Menu
      view: "Menu"
    2:
      text: NPM list
      command: "npm ls"
    3:
      text: NPM Install
      template: 'npm i '
    4:
      text: Main
      view: "Main"
    5:
      text: Main
      view: "Main"
      color: green

  "ZPM":
    1:
      text: Menu
      view: "Menu"
    2:
      text: Upgrade Plugins
      command: "zpm upgrade"
    3:
      text: Clean Cache
      command: "zpm clean"
    4:
      text: Readme
      template: "zpm readme"
    5:
      text: Main
      view: "Main"
      color: green
